"""empty message

Revision ID: 29665dba8dc4
Revises: a76f04bc9041
Create Date: 2024-05-28 14:01:11.243014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29665dba8dc4'
down_revision = 'a76f04bc9041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
