"""empty message

Revision ID: 554b742cb755
Revises: 76f76f11cb83
Create Date: 2022-08-03 10:21:48.294943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554b742cb755'
down_revision = '76f76f11cb83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('availableScienceCourses', sa.String(), nullable=True))
    op.add_column('results', sa.Column('course', sa.String(), nullable=True))
    op.add_column('results', sa.Column('eligibleCourses', sa.String(), nullable=True))
    op.add_column('results', sa.Column('otherAvailableCourses', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'otherAvailableCourses')
    op.drop_column('results', 'eligibleCourses')
    op.drop_column('results', 'course')
    op.drop_column('results', 'availableScienceCourses')
    # ### end Alembic commands ###
