"""empty message

Revision ID: ba1dcdb572f9
Revises: fd3c7d0514b3
Create Date: 2021-11-11 14:12:01.303723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1dcdb572f9'
down_revision = 'fd3c7d0514b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('electives')
    # ### end Alembic commands ###
